url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Collin Cunneely" # the name of your site, e.g. ACME Corp.
description: "a personal website"
